include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
  plugins:
    - custom_lint

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    omit_local_variable_types: true
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    unawaited_futures: true
    unnecessary_await_in_return: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  exclude:
    all:
      - "/localization/"
    unused-code:
      - "/**"
    metrics:
      - test/**
  extends:
    - recommended
  rules:
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    - no-boolean-literal-compare
    - avoid-redundant-else
    - avoid-incomplete-copy-with
    - avoid-self-compare
    - avoid-self-assignment
    - avoid-unnecessary-nullable-return-type
    - prefer-match-file-name: false
    - prefer-single-widget-per-file: false
    - unnecessary-trailing-comma: false
    - avoid-passing-self-as-argument: false
    - avoid-shadowing: false
    - prefer-declaring-const-constructor: false
    - avoid-throw-objects-without-tostring: false
    - avoid-dynamic: false
    - avoid-unsafe-collection-methods: false
    - prefer-trailing-comma: false
    - prefer-correct-callback-field-name: false
