// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'article_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_ArticleDTO _$$_ArticleDTOFromJson(Map<String, dynamic> json) =>
    _$_ArticleDTO(
      id: json['ARTICULO_ID'] as String,
      descriptionES: json['DESCRIPCION_ES'] as String,
      descriptionEN: json['DESCRIPCION_EN'] as String?,
      descriptionFR: json['DESCRIPCION_FR'] as String?,
      descriptionDE: json['DESCRIPCION_DE'] as String?,
      descriptionCA: json['DESCRIPCION_CA'] as String?,
      descriptionGB: json['DESCRIPCION_GB'] as String?,
      descriptionHU: json['DESCRIPCION_HU'] as String?,
      descriptionIT: json['DESCRIPCION_IT'] as String?,
      descriptionNL: json['DESCRIPCION_NL'] as String?,
      descriptionPL: json['DESCRIPCION_PL'] as String?,
      descriptionPT: json['DESCRIPCION_PT'] as String?,
      descriptionRO: json['DESCRIPCION_RO'] as String?,
      descriptionRU: json['DESCRIPCION_RU'] as String?,
      descriptionCN: json['DESCRIPCION_CN'] as String?,
      descriptionEL: json['DESCRIPCION_EL'] as String?,
      familyId: json['FAMILIA_ID'] as String?,
      subfamilyId: json['SUBFAMILIA_ID'] as String?,
      minimumSales: (json['VENTA_MINIMO'] as num).toDouble(),
      multipleSales: (json['VENTA_MULTIPLO'] as num).toDouble(),
      subboxUnits: (json['UNIDADES_SUBCAJA'] as num).toDouble(),
      boxUnits: (json['UNIDADES_CAJA'] as num).toDouble(),
      paletUnits: (json['UNIDADES_PALET'] as num).toDouble(),
      isActiveWeb: json['ACTIVO_WEB'] as String,
      isActiveApp: json['ACTIVO_APP'] as String,
      inCatalogue: json['EN_CATALOGO'] as String,
      discontinued: json['DESCATALOGADO'] as String,
      cataloguePage: json['PAGINA_EN_CATALOGO'] as String?,
      cataloguePage2: json['PAGINA_EN_CATALOGO2'] as String?,
      weightKg: (json['PESO_KG'] as num).toDouble(),
      largeCm: (json['LARGO_CM'] as num).toDouble(),
      widthCm: (json['ANCHO_CM'] as num).toDouble(),
      heightCm: (json['ALTO_CM'] as num).toDouble(),
      summaryES: json['SUMMARY_ES'] as String?,
      summaryEN: json['SUMMARY_EN'] as String?,
      summaryFR: json['SUMMARY_FR'] as String?,
      summaryDE: json['SUMMARY_DE'] as String?,
      summaryCA: json['SUMMARY_CA'] as String?,
      summaryGB: json['SUMMARY_GB'] as String?,
      summaryHU: json['SUMMARY_HU'] as String?,
      summaryIT: json['SUMMARY_IT'] as String?,
      summaryNL: json['SUMMARY_NL'] as String?,
      summaryPL: json['SUMMARY_PL'] as String?,
      summaryPT: json['SUMMARY_PT'] as String?,
      summaryRO: json['SUMMARY_RO'] as String?,
      summaryRU: json['SUMMARY_RU'] as String?,
      summaryCN: json['SUMMARY_CN'] as String?,
      summaryEL: json['SUMMARY_EL'] as String?,
      availableStock: (json['STOCK_DISPONIBLE'] as num?)?.toDouble(),
      currentSales: (json['VENTAS_ACTUAL'] as num?)?.toDouble(),
      previousSales: (json['VENTAS_ANTERIOR'] as num?)?.toDouble(),
      purchasesDeliveryQuantity1:
          (json['COMPRAS_ENTREGA_CANTIDAD_1'] as num?)?.toDouble(),
      purchasesDeliveryQuantity2:
          (json['COMPRAS_ENTREGA_CANTIDAD_2'] as num?)?.toDouble(),
      purchasesDeliveryQuantity3:
          (json['COMPRAS_ENTREGA_CANTIDAD_3'] as num?)?.toDouble(),
      purchasesDeliveryQuantityMore3:
          (json['COMPRAS_ENTREGA_CANTIDAD_MAS_3'] as num?)?.toDouble(),
      purchasesDeliveryDate1: json['COMPRAS_ENTREGA_FECHA_1'] == null
          ? null
          : DateTime.parse(json['COMPRAS_ENTREGA_FECHA_1'] as String),
      purchasesDeliveryDate2: json['COMPRAS_ENTREGA_FECHA_2'] == null
          ? null
          : DateTime.parse(json['COMPRAS_ENTREGA_FECHA_2'] as String),
      purchasesDeliveryDate3: json['COMPRAS_ENTREGA_FECHA_3'] == null
          ? null
          : DateTime.parse(json['COMPRAS_ENTREGA_FECHA_3'] as String),
      purchasesDeliveryStatus1: json['COMPRAS_ENTREGA_ESTADO_1'] as String?,
      purchasesDeliveryStatus2: json['COMPRAS_ENTREGA_ESTADO_2'] as String?,
      purchasesDeliveryStatus3: json['COMPRAS_ENTREGA_ESTADO_'] as String?,
      principalImage: json['IMAGEN_PRINCIPAL'] as String?,
      lastUpdated: DateTime.parse(json['LAST_UPDATED'] as String),
      deleted: json['DELETED'] as String? ?? 'N',
    );

Map<String, dynamic> _$$_ArticleDTOToJson(_$_ArticleDTO instance) =>
    <String, dynamic>{
      'ARTICULO_ID': instance.id,
      'DESCRIPCION_ES': instance.descriptionES,
      'DESCRIPCION_EN': instance.descriptionEN,
      'DESCRIPCION_FR': instance.descriptionFR,
      'DESCRIPCION_DE': instance.descriptionDE,
      'DESCRIPCION_CA': instance.descriptionCA,
      'DESCRIPCION_GB': instance.descriptionGB,
      'DESCRIPCION_HU': instance.descriptionHU,
      'DESCRIPCION_IT': instance.descriptionIT,
      'DESCRIPCION_NL': instance.descriptionNL,
      'DESCRIPCION_PL': instance.descriptionPL,
      'DESCRIPCION_PT': instance.descriptionPT,
      'DESCRIPCION_RO': instance.descriptionRO,
      'DESCRIPCION_RU': instance.descriptionRU,
      'DESCRIPCION_CN': instance.descriptionCN,
      'DESCRIPCION_EL': instance.descriptionEL,
      'FAMILIA_ID': instance.familyId,
      'SUBFAMILIA_ID': instance.subfamilyId,
      'VENTA_MINIMO': instance.minimumSales,
      'VENTA_MULTIPLO': instance.multipleSales,
      'UNIDADES_SUBCAJA': instance.subboxUnits,
      'UNIDADES_CAJA': instance.boxUnits,
      'UNIDADES_PALET': instance.paletUnits,
      'ACTIVO_WEB': instance.isActiveWeb,
      'ACTIVO_APP': instance.isActiveApp,
      'EN_CATALOGO': instance.inCatalogue,
      'DESCATALOGADO': instance.discontinued,
      'PAGINA_EN_CATALOGO': instance.cataloguePage,
      'PAGINA_EN_CATALOGO2': instance.cataloguePage2,
      'PESO_KG': instance.weightKg,
      'LARGO_CM': instance.largeCm,
      'ANCHO_CM': instance.widthCm,
      'ALTO_CM': instance.heightCm,
      'SUMMARY_ES': instance.summaryES,
      'SUMMARY_EN': instance.summaryEN,
      'SUMMARY_FR': instance.summaryFR,
      'SUMMARY_DE': instance.summaryDE,
      'SUMMARY_CA': instance.summaryCA,
      'SUMMARY_GB': instance.summaryGB,
      'SUMMARY_HU': instance.summaryHU,
      'SUMMARY_IT': instance.summaryIT,
      'SUMMARY_NL': instance.summaryNL,
      'SUMMARY_PL': instance.summaryPL,
      'SUMMARY_PT': instance.summaryPT,
      'SUMMARY_RO': instance.summaryRO,
      'SUMMARY_RU': instance.summaryRU,
      'SUMMARY_CN': instance.summaryCN,
      'SUMMARY_EL': instance.summaryEL,
      'STOCK_DISPONIBLE': instance.availableStock,
      'VENTAS_ACTUAL': instance.currentSales,
      'VENTAS_ANTERIOR': instance.previousSales,
      'COMPRAS_ENTREGA_CANTIDAD_1': instance.purchasesDeliveryQuantity1,
      'COMPRAS_ENTREGA_CANTIDAD_2': instance.purchasesDeliveryQuantity2,
      'COMPRAS_ENTREGA_CANTIDAD_3': instance.purchasesDeliveryQuantity3,
      'COMPRAS_ENTREGA_CANTIDAD_MAS_3': instance.purchasesDeliveryQuantityMore3,
      'COMPRAS_ENTREGA_FECHA_1':
          instance.purchasesDeliveryDate1?.toIso8601String(),
      'COMPRAS_ENTREGA_FECHA_2':
          instance.purchasesDeliveryDate2?.toIso8601String(),
      'COMPRAS_ENTREGA_FECHA_3':
          instance.purchasesDeliveryDate3?.toIso8601String(),
      'COMPRAS_ENTREGA_ESTADO_1': instance.purchasesDeliveryStatus1,
      'COMPRAS_ENTREGA_ESTADO_2': instance.purchasesDeliveryStatus2,
      'COMPRAS_ENTREGA_ESTADO_': instance.purchasesDeliveryStatus3,
      'IMAGEN_PRINCIPAL': instance.principalImage,
      'LAST_UPDATED': instance.lastUpdated.toIso8601String(),
      'DELETED': instance.deleted,
    };
