import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:jbm_nikel_mobile/src/core/domain/familia.dart';
import 'package:money2/money2.dart';

import '../../../core/domain/subfamilia.dart';

part 'articulo.freezed.dart';

@freezed
class Articulo with _$Articulo {
  const Articulo._();
  const factory Articulo(
      {required String id,
      required String descripcionES,
      String? descripcionEN,
      String? descripcionFR,
      String? descripcionDE,
      String? descripcionCA,
      String? descripcionGB,
      String? descripcionHU,
      String? descripcionIT,
      String? descripcionNL,
      String? descripcionPL,
      String? descripcionPT,
      String? descripcionRO,
      String? descripcionRU,
      String? descripcionCN,
      String? descripcionEL,
      Familia? familia,
      Subfamilia? subfamilia,
      required int ventaMinimo,
      required int ventaMultiplo,
      required int unidadesSubcaja,
      required int unidadesCaja,
      required int unidadesPalet,
      required bool activoWeb,
      required bool activoApp,
      required bool enCatalogo,
      required bool descatalogado,
      String? paginaEnCatalgo,
      String? paginaEnCatalgo2,
      required double pesoKg,
      required double largoCm,
      required double anchoCm,
      required double altoCm,
      String? resumenES,
      String? resumenEN,
      String? resumenFR,
      String? resumenDE,
      String? resumenCA,
      String? resumenGB,
      String? resumenHU,
      String? resumenIT,
      String? resumenNL,
      String? resumenPL,
      String? resumenPT,
      String? resumenRO,
      String? resumenRU,
      String? resumenCN,
      String? resumenEL,
      required int stockDisponible,
      required Money ventasActual,
      required Money ventasAnterior,
      required int comprasEntregaCantidad1,
      required int comprasEntregaCantidad2,
      required int comprasEntregaCantidad3,
      required int comprasEntregaCantidadMas3,
      DateTime? comprasEntregaFecha1,
      DateTime? comprasEntregaFecha2,
      DateTime? comprasEntregaFecha3,
      String? comprasEntregaEstado1,
      String? comprasEntregaEstado2,
      String? comprasEntregaEstado3,
      String? imagenPrincipal,
      String? gtin13Unidad,
      String? gs1128Subcaja,
      String? gs1128Caja,
      String? gs1128Palet,
      int? ventasOrden,
      required Money ventasAnyoActual,
      required Money ventasAnyoAnterior,
      required Money ventasHaceDosAnyos,
      required double margenAnyoActual,
      required double margenAnyoAnterior,
      required double margenHaceDosAnyos,
      required DateTime lastUpdated,
      required bool deleted}) = _Articulo;
}
