// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'articulo_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ArticuloDTOImpl _$$ArticuloDTOImplFromJson(
  Map<String, dynamic> json,
) => _$ArticuloDTOImpl(
  id: json['ARTICULO_ID'] as String,
  descripcionES: json['DESCRIPCION_ES'] as String,
  descripcionEN: json['DESCRIPCION_EN'] as String?,
  descripcionFR: json['DESCRIPCION_FR'] as String?,
  descripcionDE: json['DESCRIPCION_DE'] as String?,
  descripcionCA: json['DESCRIPCION_CA'] as String?,
  descripcionGB: json['DESCRIPCION_GB'] as String?,
  descripcionHU: json['DESCRIPCION_HU'] as String?,
  descripcionIT: json['DESCRIPCION_IT'] as String?,
  descripcionNL: json['DESCRIPCION_NL'] as String?,
  descripcionPL: json['DESCRIPCION_PL'] as String?,
  descripcionPT: json['DESCRIPCION_PT'] as String?,
  descripcionRO: json['DESCRIPCION_RO'] as String?,
  descripcionRU: json['DESCRIPCION_RU'] as String?,
  descripcionCN: json['DESCRIPCION_CN'] as String?,
  descripcionEL: json['DESCRIPCION_EL'] as String?,
  familiaId: json['FAMILIA_ID'] as String?,
  subfamiliaId: json['SUBFAMILIA_ID'] as String?,
  ventaMinimo: (json['VENTA_MINIMO'] as num).toInt(),
  ventaMultiplo: (json['VENTA_MULTIPLO'] as num).toInt(),
  unidadesSubcaja: (json['UNIDADES_SUBCAJA'] as num).toInt(),
  unidadesCaja: (json['UNIDADES_CAJA'] as num).toInt(),
  unidadesPalet: (json['UNIDADES_PALET'] as num).toInt(),
  activoWeb: json['ACTIVO_WEB'] as String,
  activoApp: json['ACTIVO_APP'] as String,
  enCatalogo: json['EN_CATALOGO'] as String,
  descatalogado: json['DESCATALOGADO'] as String,
  paginaEnCatalgo: json['PAGINA_EN_CATALOGO'] as String?,
  paginaEnCatalgo2: json['PAGINA_EN_CATALOGO2'] as String?,
  pesoKg: (json['PESO_KG'] as num).toDouble(),
  largoCm: (json['LARGO_CM'] as num).toDouble(),
  anchoCm: (json['ANCHO_CM'] as num).toDouble(),
  altoCm: (json['ALTO_CM'] as num).toDouble(),
  resumenES: json['RESUMEN_ES'] as String?,
  resumenEN: json['RESUMEN_EN'] as String?,
  resumenFR: json['RESUMEN_FR'] as String?,
  resumenDE: json['RESUMEN_DE'] as String?,
  resumenCA: json['RESUMEN_CA'] as String?,
  resumenGB: json['RESUMEN_GB'] as String?,
  resumenHU: json['RESUMEN_HU'] as String?,
  resumenIT: json['RESUMEN_IT'] as String?,
  resumenNL: json['RESUMEN_NL'] as String?,
  resumenPL: json['RESUMEN_PL'] as String?,
  resumenPT: json['RESUMEN_PT'] as String?,
  resumenRO: json['RESUMEN_RO'] as String?,
  resumenRU: json['RESUMEN_RU'] as String?,
  resumenCN: json['RESUMEN_CN'] as String?,
  resumenEL: json['RESUMEN_EL'] as String?,
  stockDisponible: (json['STOCK_DISPONIBLE'] as num).toInt(),
  ventasActual: (json['VENTAS_ACTUAL'] as num).toDouble(),
  ventasAnterior: (json['VENTAS_ANTERIOR'] as num).toDouble(),
  comprasEntregaCantidad1: (json['COMPRAS_ENTREGA_CANTIDAD_1'] as num).toInt(),
  comprasEntregaCantidad2: (json['COMPRAS_ENTREGA_CANTIDAD_2'] as num).toInt(),
  comprasEntregaCantidad3: (json['COMPRAS_ENTREGA_CANTIDAD_3'] as num).toInt(),
  comprasEntregaCantidadMas3:
      (json['COMPRAS_ENTREGA_CANTIDAD_MAS_3'] as num).toInt(),
  comprasEntregaFecha1:
      json['COMPRAS_ENTREGA_FECHA_1'] == null
          ? null
          : DateTime.parse(json['COMPRAS_ENTREGA_FECHA_1'] as String),
  comprasEntregaFecha2:
      json['COMPRAS_ENTREGA_FECHA_2'] == null
          ? null
          : DateTime.parse(json['COMPRAS_ENTREGA_FECHA_2'] as String),
  comprasEntregaFecha3:
      json['COMPRAS_ENTREGA_FECHA_3'] == null
          ? null
          : DateTime.parse(json['COMPRAS_ENTREGA_FECHA_3'] as String),
  comprasEntregaEstado1: json['COMPRAS_ENTREGA_ESTADO_1'] as String?,
  comprasEntregaEstado2: json['COMPRAS_ENTREGA_ESTADO_2'] as String?,
  comprasEntregaEstado3: json['COMPRAS_ENTREGA_ESTADO_'] as String?,
  imagenPrincipal: json['IMAGEN_PRINCIPAL'] as String?,
  gtin13Unidad: json['GTIN_13_UNIDAD'] as String?,
  gs1128Subcaja: json['GS1_128_SUBCAJA'] as String?,
  gs1128Caja: json['GS1_128_CAJA'] as String?,
  gs1128Palet: json['GS1_128_PALET'] as String?,
  ventasOrden: (json['VENTAS_ORDEN'] as num?)?.toInt(),
  lastUpdated: DateTime.parse(json['LAST_UPDATED'] as String),
  deleted: json['DELETED'] as String? ?? 'N',
);

Map<String, dynamic> _$$ArticuloDTOImplToJson(
  _$ArticuloDTOImpl instance,
) => <String, dynamic>{
  'ARTICULO_ID': instance.id,
  'DESCRIPCION_ES': instance.descripcionES,
  'DESCRIPCION_EN': instance.descripcionEN,
  'DESCRIPCION_FR': instance.descripcionFR,
  'DESCRIPCION_DE': instance.descripcionDE,
  'DESCRIPCION_CA': instance.descripcionCA,
  'DESCRIPCION_GB': instance.descripcionGB,
  'DESCRIPCION_HU': instance.descripcionHU,
  'DESCRIPCION_IT': instance.descripcionIT,
  'DESCRIPCION_NL': instance.descripcionNL,
  'DESCRIPCION_PL': instance.descripcionPL,
  'DESCRIPCION_PT': instance.descripcionPT,
  'DESCRIPCION_RO': instance.descripcionRO,
  'DESCRIPCION_RU': instance.descripcionRU,
  'DESCRIPCION_CN': instance.descripcionCN,
  'DESCRIPCION_EL': instance.descripcionEL,
  'FAMILIA_ID': instance.familiaId,
  'SUBFAMILIA_ID': instance.subfamiliaId,
  'VENTA_MINIMO': instance.ventaMinimo,
  'VENTA_MULTIPLO': instance.ventaMultiplo,
  'UNIDADES_SUBCAJA': instance.unidadesSubcaja,
  'UNIDADES_CAJA': instance.unidadesCaja,
  'UNIDADES_PALET': instance.unidadesPalet,
  'ACTIVO_WEB': instance.activoWeb,
  'ACTIVO_APP': instance.activoApp,
  'EN_CATALOGO': instance.enCatalogo,
  'DESCATALOGADO': instance.descatalogado,
  'PAGINA_EN_CATALOGO': instance.paginaEnCatalgo,
  'PAGINA_EN_CATALOGO2': instance.paginaEnCatalgo2,
  'PESO_KG': instance.pesoKg,
  'LARGO_CM': instance.largoCm,
  'ANCHO_CM': instance.anchoCm,
  'ALTO_CM': instance.altoCm,
  'RESUMEN_ES': instance.resumenES,
  'RESUMEN_EN': instance.resumenEN,
  'RESUMEN_FR': instance.resumenFR,
  'RESUMEN_DE': instance.resumenDE,
  'RESUMEN_CA': instance.resumenCA,
  'RESUMEN_GB': instance.resumenGB,
  'RESUMEN_HU': instance.resumenHU,
  'RESUMEN_IT': instance.resumenIT,
  'RESUMEN_NL': instance.resumenNL,
  'RESUMEN_PL': instance.resumenPL,
  'RESUMEN_PT': instance.resumenPT,
  'RESUMEN_RO': instance.resumenRO,
  'RESUMEN_RU': instance.resumenRU,
  'RESUMEN_CN': instance.resumenCN,
  'RESUMEN_EL': instance.resumenEL,
  'STOCK_DISPONIBLE': instance.stockDisponible,
  'VENTAS_ACTUAL': instance.ventasActual,
  'VENTAS_ANTERIOR': instance.ventasAnterior,
  'COMPRAS_ENTREGA_CANTIDAD_1': instance.comprasEntregaCantidad1,
  'COMPRAS_ENTREGA_CANTIDAD_2': instance.comprasEntregaCantidad2,
  'COMPRAS_ENTREGA_CANTIDAD_3': instance.comprasEntregaCantidad3,
  'COMPRAS_ENTREGA_CANTIDAD_MAS_3': instance.comprasEntregaCantidadMas3,
  'COMPRAS_ENTREGA_FECHA_1': instance.comprasEntregaFecha1?.toIso8601String(),
  'COMPRAS_ENTREGA_FECHA_2': instance.comprasEntregaFecha2?.toIso8601String(),
  'COMPRAS_ENTREGA_FECHA_3': instance.comprasEntregaFecha3?.toIso8601String(),
  'COMPRAS_ENTREGA_ESTADO_1': instance.comprasEntregaEstado1,
  'COMPRAS_ENTREGA_ESTADO_2': instance.comprasEntregaEstado2,
  'COMPRAS_ENTREGA_ESTADO_': instance.comprasEntregaEstado3,
  'IMAGEN_PRINCIPAL': instance.imagenPrincipal,
  'GTIN_13_UNIDAD': instance.gtin13Unidad,
  'GS1_128_SUBCAJA': instance.gs1128Subcaja,
  'GS1_128_CAJA': instance.gs1128Caja,
  'GS1_128_PALET': instance.gs1128Palet,
  'VENTAS_ORDEN': instance.ventasOrden,
  'LAST_UPDATED': instance.lastUpdated.toIso8601String(),
  'DELETED': instance.deleted,
};
