// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'articulo_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_ArticuloDTO _$$_ArticuloDTOFromJson(Map<String, dynamic> json) =>
    _$_ArticuloDTO(
      id: json['ARTICULO_ID'] as String,
      descripcionES: json['DESCRIPCION_ES'] as String,
      descripcionEN: json['DESCRIPCION_EN'] as String?,
      descripcionFR: json['DESCRIPCION_FR'] as String?,
      descripcionDE: json['DESCRIPCION_DE'] as String?,
      descripcionCA: json['DESCRIPCION_CA'] as String?,
      descripcionGB: json['DESCRIPCION_GB'] as String?,
      descripcionHU: json['DESCRIPCION_HU'] as String?,
      descripcionIT: json['DESCRIPCION_IT'] as String?,
      descripcionNL: json['DESCRIPCION_NL'] as String?,
      descripcionPL: json['DESCRIPCION_PL'] as String?,
      descripcionPT: json['DESCRIPCION_PT'] as String?,
      descripcionRO: json['DESCRIPCION_RO'] as String?,
      descripcionRU: json['DESCRIPCION_RU'] as String?,
      descripcionCN: json['DESCRIPCION_CN'] as String?,
      descripcionEL: json['DESCRIPCION_EL'] as String?,
      familiaId: json['FAMILIA_ID'] as String?,
      subfamiliaId: json['SUBFAMILIA_ID'] as String?,
      ventaMinimo: (json['VENTA_MINIMO'] as num).toDouble(),
      ventaMultiplo: (json['VENTA_MULTIPLO'] as num).toDouble(),
      unidadesSubcaja: (json['UNIDADES_SUBCAJA'] as num).toDouble(),
      unidadesCaja: (json['UNIDADES_CAJA'] as num).toDouble(),
      unidadesPalet: (json['UNIDADES_PALET'] as num).toDouble(),
      activoWeb: json['ACTIVO_WEB'] as String,
      activoApp: json['ACTIVO_APP'] as String,
      enCatalogo: json['EN_CATALOGO'] as String,
      descatalogado: json['DESCATALOGADO'] as String,
      paginaEnCatalgo: json['PAGINA_EN_CATALOGO'] as String?,
      paginaEnCatalgo2: json['PAGINA_EN_CATALOGO2'] as String?,
      pesoKg: (json['PESO_KG'] as num).toDouble(),
      largoCm: (json['LARGO_CM'] as num).toDouble(),
      anchoCm: (json['ANCHO_CM'] as num).toDouble(),
      altoCm: (json['ALTO_CM'] as num).toDouble(),
      resumenES: json['SUMMARY_ES'] as String?,
      resumenEN: json['SUMMARY_EN'] as String?,
      resumenFR: json['SUMMARY_FR'] as String?,
      resumenDE: json['SUMMARY_DE'] as String?,
      resumenCA: json['SUMMARY_CA'] as String?,
      resumenGB: json['SUMMARY_GB'] as String?,
      resumenHU: json['SUMMARY_HU'] as String?,
      resumenIT: json['SUMMARY_IT'] as String?,
      resumenNL: json['SUMMARY_NL'] as String?,
      resumenPL: json['SUMMARY_PL'] as String?,
      resumenPT: json['SUMMARY_PT'] as String?,
      resumenRO: json['SUMMARY_RO'] as String?,
      resumenRU: json['SUMMARY_RU'] as String?,
      resumenCN: json['SUMMARY_CN'] as String?,
      resumenEL: json['SUMMARY_EL'] as String?,
      stockDisponible: (json['STOCK_DISPONIBLE'] as num?)?.toDouble(),
      ventasActual: (json['VENTAS_ACTUAL'] as num?)?.toDouble(),
      ventasAnterior: (json['VENTAS_ANTERIOR'] as num?)?.toDouble(),
      comprasEntregaCantidad1:
          (json['COMPRAS_ENTREGA_CANTIDAD_1'] as num?)?.toDouble(),
      comprasEntregaCantidad2:
          (json['COMPRAS_ENTREGA_CANTIDAD_2'] as num?)?.toDouble(),
      comprasEntregaCantidad3:
          (json['COMPRAS_ENTREGA_CANTIDAD_3'] as num?)?.toDouble(),
      comprasEntregaCantidadMas3:
          (json['COMPRAS_ENTREGA_CANTIDAD_MAS_3'] as num?)?.toDouble(),
      comprasEntregaFecha1: json['COMPRAS_ENTREGA_FECHA_1'] == null
          ? null
          : DateTime.parse(json['COMPRAS_ENTREGA_FECHA_1'] as String),
      comprasEntregaFecha2: json['COMPRAS_ENTREGA_FECHA_2'] == null
          ? null
          : DateTime.parse(json['COMPRAS_ENTREGA_FECHA_2'] as String),
      comprasEntregaFecha3: json['COMPRAS_ENTREGA_FECHA_3'] == null
          ? null
          : DateTime.parse(json['COMPRAS_ENTREGA_FECHA_3'] as String),
      comprasEntregaEstado1: json['COMPRAS_ENTREGA_ESTADO_1'] as String?,
      comprasEntregaEstado2: json['COMPRAS_ENTREGA_ESTADO_2'] as String?,
      comprasEntregaEstado3: json['COMPRAS_ENTREGA_ESTADO_'] as String?,
      imagenPrincipal: json['IMAGEN_PRINCIPAL'] as String?,
      lastUpdated: DateTime.parse(json['LAST_UPDATED'] as String),
      deleted: json['DELETED'] as String? ?? 'N',
    );

Map<String, dynamic> _$$_ArticuloDTOToJson(_$_ArticuloDTO instance) =>
    <String, dynamic>{
      'ARTICULO_ID': instance.id,
      'DESCRIPCION_ES': instance.descripcionES,
      'DESCRIPCION_EN': instance.descripcionEN,
      'DESCRIPCION_FR': instance.descripcionFR,
      'DESCRIPCION_DE': instance.descripcionDE,
      'DESCRIPCION_CA': instance.descripcionCA,
      'DESCRIPCION_GB': instance.descripcionGB,
      'DESCRIPCION_HU': instance.descripcionHU,
      'DESCRIPCION_IT': instance.descripcionIT,
      'DESCRIPCION_NL': instance.descripcionNL,
      'DESCRIPCION_PL': instance.descripcionPL,
      'DESCRIPCION_PT': instance.descripcionPT,
      'DESCRIPCION_RO': instance.descripcionRO,
      'DESCRIPCION_RU': instance.descripcionRU,
      'DESCRIPCION_CN': instance.descripcionCN,
      'DESCRIPCION_EL': instance.descripcionEL,
      'FAMILIA_ID': instance.familiaId,
      'SUBFAMILIA_ID': instance.subfamiliaId,
      'VENTA_MINIMO': instance.ventaMinimo,
      'VENTA_MULTIPLO': instance.ventaMultiplo,
      'UNIDADES_SUBCAJA': instance.unidadesSubcaja,
      'UNIDADES_CAJA': instance.unidadesCaja,
      'UNIDADES_PALET': instance.unidadesPalet,
      'ACTIVO_WEB': instance.activoWeb,
      'ACTIVO_APP': instance.activoApp,
      'EN_CATALOGO': instance.enCatalogo,
      'DESCATALOGADO': instance.descatalogado,
      'PAGINA_EN_CATALOGO': instance.paginaEnCatalgo,
      'PAGINA_EN_CATALOGO2': instance.paginaEnCatalgo2,
      'PESO_KG': instance.pesoKg,
      'LARGO_CM': instance.largoCm,
      'ANCHO_CM': instance.anchoCm,
      'ALTO_CM': instance.altoCm,
      'SUMMARY_ES': instance.resumenES,
      'SUMMARY_EN': instance.resumenEN,
      'SUMMARY_FR': instance.resumenFR,
      'SUMMARY_DE': instance.resumenDE,
      'SUMMARY_CA': instance.resumenCA,
      'SUMMARY_GB': instance.resumenGB,
      'SUMMARY_HU': instance.resumenHU,
      'SUMMARY_IT': instance.resumenIT,
      'SUMMARY_NL': instance.resumenNL,
      'SUMMARY_PL': instance.resumenPL,
      'SUMMARY_PT': instance.resumenPT,
      'SUMMARY_RO': instance.resumenRO,
      'SUMMARY_RU': instance.resumenRU,
      'SUMMARY_CN': instance.resumenCN,
      'SUMMARY_EL': instance.resumenEL,
      'STOCK_DISPONIBLE': instance.stockDisponible,
      'VENTAS_ACTUAL': instance.ventasActual,
      'VENTAS_ANTERIOR': instance.ventasAnterior,
      'COMPRAS_ENTREGA_CANTIDAD_1': instance.comprasEntregaCantidad1,
      'COMPRAS_ENTREGA_CANTIDAD_2': instance.comprasEntregaCantidad2,
      'COMPRAS_ENTREGA_CANTIDAD_3': instance.comprasEntregaCantidad3,
      'COMPRAS_ENTREGA_CANTIDAD_MAS_3': instance.comprasEntregaCantidadMas3,
      'COMPRAS_ENTREGA_FECHA_1':
          instance.comprasEntregaFecha1?.toIso8601String(),
      'COMPRAS_ENTREGA_FECHA_2':
          instance.comprasEntregaFecha2?.toIso8601String(),
      'COMPRAS_ENTREGA_FECHA_3':
          instance.comprasEntregaFecha3?.toIso8601String(),
      'COMPRAS_ENTREGA_ESTADO_1': instance.comprasEntregaEstado1,
      'COMPRAS_ENTREGA_ESTADO_2': instance.comprasEntregaEstado2,
      'COMPRAS_ENTREGA_ESTADO_': instance.comprasEntregaEstado3,
      'IMAGEN_PRINCIPAL': instance.imagenPrincipal,
      'LAST_UPDATED': instance.lastUpdated.toIso8601String(),
      'DELETED': instance.deleted,
    };
